config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :images
  end
  resource  :session
  resources :comments
  resources :taggings
  resources :tags
  
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/welcome'
  root to: 'pages#explore'
  

end

app/models/image.rb
class Image < ActiveRecord::Base
  #attr_accessible :filepicker_url
  
  validates :filepicker_url, presence: true
  
  belongs_to(
    :poster,
    class_name: "User",
    foreign_key: :user_id,
    primary_key: :id
  )
  
  has_many(
    :taggings,
    class_name: "Tagging",
    foreign_key: :image_id,
    primary_key: :id
  )
  
  def self.load_metadata(image)
    metadata_url = image.filepicker_url + "/metadata?width=true&height=true"
    res = RestClient.get metadata_url
    if res.code == 200
      hash = JSON.parse res # .body?
      # fail
      image.width = hash["width"]
      image.height = hash["height"]
      return true
    end
    return false
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    @image = Image.new(image_params)
    @image.user_id = current_user.id
    Image.load_metadata(@image)
    @image.save!
    
    # render :json => @image
    redirect_to user_image_path(id: @image.id)
  end

  def show
    @shown_user = User.find_by_id(params[:user_id])
    shown_image_id = params[:id]
    @image = Image.find_by(user_id: @shown_user.id, id: shown_image_id)
    @comments = Comment.where(image_id: shown_image_id)
    @taggings = @image.taggings
    # arbitrary max dimensions, from a browser on my dev sys: 900 x 400. eh. giving room for error...
    # TODO: constants.
    @image_url = my_image_url(@image, 600)
    @page_title = "#{ @image.title } by #{ @shown_user.username }"
  end

  def new
    redirect_to pages_welcome_url unless logged_in?
    
    @image = Image.new()
  end

  def update
  end
  
  def index
    render :json => Image.all
  end
  
  def destroy
    @image = Image.find_by(id: params[:id])
     
    if (@image.poster == current_user)
      # yay!
      @image.destroy!
      flash[:notices] = ["Image removed!"]
      redirect_to user_url(current_user)
    else
      # nope!
      flash[:errors] = ["Not your picture to delete!"]
      redirect_to :back
    end
  end

  private
  
  def image_params
    params.require(:image).permit(:title, :description, :filepicker_url)
  end
  
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_image.html.erb
    <% user = User.find_by_id(image.user_id) %>
      <a href="<%= user_image_url(user, image) %>" class="pic ">
        <img 
          src="<%= my_image_url(image, 300) %>"
          class="image-thumbnail"
          data-toggle="tooltip" 
          data-placement="top" 
          title='<%= image.title %> by <%= user.username %>'
          alt='<%= image.title %> by <%= user.username %>'
          >
      </a>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/new.html.erb
<div class="row">
  <div class="col-xs-6 col-xs-offset-2">
    <h1>Upload an image!</h1>
    <form action="<%= user_images_url(current_user) %>" method="post" role="form">
      <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      <script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>
      <script>
        filepicker.setKey("ApZjrxYjxQCKbJDoJEQnDz")
        function uploadComplete() {
          console.log ("uploaded!");
          var $button = $("#filepickerButton~button:first-of-type");
          $button.text("Image uploaded!");
          $button.addClass("disabled");
        }
      </script>
      <input 
        type="filepicker"
        data-fp-mimetypes="image/*"
        data-fp-container="modal"
        class="btn btn-primary"
        data-fp-button-text="Choose image"
        name="image[filepicker_url]"
        onchange=uploadComplete()
        id="filepickerButton" 
      > 
      
      <div class="form-group" for="title">
        <label>
          Title
        </label>
          
        <input type="text" name="image[title]" value="" class="form-control" id="title">
      </div>
  
      <div class="form-group">
        <label class="form-group">
          Description
        </label>
          
        <textarea name="image[description]" value="" class="form-control" id="description" rows="5"></textarea>
        </label>
      </div>
  
      <button type="submit" value="" class="btn btn-primary">Post image</button>
    </form>
  </div><!-- /col-xs-4 -->
</div><!-- /row -->  

app/views/images/show.html.erb
    <div class="jumbotron image-backing">
      <img src="<%= @image_url %>" class="pic indiv-pic">
    </div>

<div class="container">
  <div class="row">
    <div class="page-header col-xs-9 col-offset-1">
      <h1><%= @image.title %>
      <small>Posted by <a href="<%= user_url(@shown_user) %>"><%= @shown_user.username %></a></small></h1>
    </div>
  </div>
  
  <div class="row">
    <div class="caption col-xs-9 col-offset-1">
      <p><%= @image.description %></p>
    </div>
  </div>
  
  <% if current_user == @shown_user %>
    <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteModal">
      Delete this image
    </button>
    
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <h4 class="modal-title" id="myModalLabel">Delete this image?</h4>
          </div>
          <div class="modal-body">
            Are you sure?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <a href="<%= user_image_url %>" data-method="delete"><button type="button" class="btn btn-danger">Trash it!</button></a>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  
  <h2>Tags</h2>
  <% if @taggings.empty? %>
    <h3><i>No tags yet.</i></h3>
  <% else %>
    <div class="row">
      <div class="col-xs-9 col-offset-1">
        <% @taggings.each do |tagging| %>
          <div type="button" class="btn btn-default btn-tag"><a href="<%= tag_url(tagging.tag_id) %>"><%= tagging.name %></a>
            <a href="<%= tagging_url(tagging.id) %>" data-method="delete" title="delete tag"><span class="glyphicon glyphicon-remove-circle"></span></a>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  
  <div class="row">
    <div class="caption col-xs-9 col-offset-1">
      <form action="<%= taggings_url %>" method="POST">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
      
        <input
          type="hidden"
          name="tag[image_id]"
          value="<%= @image.id %>">
        
        <input
          type="hidden"
          name="tag[image_user_id]"
          value="<%= @shown_user.id %>">
        
        <div class="form-group">
          <label>
            Leave a tag!
          </label>
        </div>
        <textarea name="tag[name]" class="form-control"></textarea>
        <input type="submit" class="btn btn-primary" value="Save tag">
      </form>
    </div>
  </div>
  
      
  <h2>Comments</h2>
  <% if @comments.empty? %>
    <h3><i>No comments yet.</i></h3>
  <% else %>
    <div class="row">
      <h2>Comments</h2>
        <% @comments.each do |comment| %>
          <% commenter = User.find_by_id(comment.user_id) %>
          <div class="media">
            <a class="pull-left" href="#">
              <img 
                class="media-object img-circle"
                src="http://placehold.it/32x32"
                alt="user pic">
            </a>
            <div class="media-body">
              <div class="media-heading">
                <a href="<%= user_url(commenter) %>">
                  <%= commenter.username %></a>
                  <%= time_ago_in_words(comment.created_at) %><br>
              </h4>
              <%= comment.body %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
  
  <div class="row">
    <div class="caption col-xs-9 col-offset-1">
      <h3>Leave a comment!</h3>
      <form action="<%= comments_url %>" method="POST">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
      
        <input
          type="hidden"
          name="comment[image_id]"
          value="<%= @image.id %>">
        
        <input
          type="hidden"
          name="comment[image_user_id]"
          value="<%= @shown_user.id %>">
        
        <div class="form-group">
          <label>
            Comment body
          </label>
        </div>
        <textarea name="comment[body]" class="form-control"></textarea>
        <input type="submit" class="btn btn-primary" value="Save comment">
      </form>
    </div>
  </div>
</div>

app/views/images/update.html.erb
<h1>Images#update</h1>
<p>Find me in app/views/images/update.html.erb</p>