config/routes.rb
Rails.application.routes.draw do
  
  resources :users do
    resources :images
  end
  resource  :session
  resources :comments
  resources :taggings
  resources :tags
  
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  get 'pages/welcome'
  root to: 'pages#explore'
  

end

app/views/layouts/_flash.html.erb
<% unless flash[:notices].nil? %>
  <% flash[:notices].each do |notice| %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
  <% end %>
<% end %>
<% unless flash[:errors].nil? %>
  <% flash[:errors].each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav nav-pills"><a href="<%= root_url %>">Home</a></li>
        
        <% if guest? %>
          <li class="dropdown nav nav-pills navbar-form">
            <button class="dropdown-toggle" type="button" id="signedInDropdown" data-toggle="dropdown">
              Signed in as: Guest
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu nav-pills nav-stacked" role="menu">
              <li><%= link_to "Sign Up", edit_user_url(current_user) %></li>
              <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
            </ul>
          </li><%# /guest %>
        <% elsif logged_in? %>
          <li class="dropdown nav nav-pills navbar-form">
            <button class="dropdown-toggle" type="button" id="signedInDropdown" data-toggle="dropdown">
              Signed in as: <%= current_user.username %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu nav-pills nav-stacked" role="menu">
              <li><%= link_to "Profile", user_url(current_user) %></li>
              <li><%= link_to "Sign Out", session_url, :method => :delete %></li>
            </ul>
          </li><%# /logged_in %>
        <% else %>
          <li class="nav nav-pills"><a href="<%= new_session_url %>">Sign In</a></li>
          <li class="nav nav-pills"><%= link_to "Sign In as Guest", users_url, method: :post %><%# /neither guest nor logged in %>
        <% end %>
        
        <% if logged_in? %>
          <li class="nav nav-pills navbar-form"><%= button_to "Upload", new_user_image_url(current_user), method: :get, class: "btn btn-primary" %></li>
          <li class="nav nav-pills">
            <a href="<%= tags_url %>">
              Popular Tags
            </a>
        <% end %>
        
        <li class="nav nav-pills"><a href="<%= pages_contact_url %>">Contact</a></li>
        <li class="nav nav-pills"><a href="<%= pages_about_url %>">About</a></li>
        
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_session.html.erb
<% if logged_in? %>
  Hello <%= current_user.username %>!
  <%= link_to "Sign Out", session_url, method: :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <% if @page_title.nil? %>
    <title>Woofr</title>
  <% else %>
    <title>Woofr &raquo; <%= @page_title %></title>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>
<%= render "layouts/flash" %>

<%= yield %>

</body>
</html>